version: '3'

services:
  app:
    image: apollo-koa-dataloader:latest
    build: .
    env_file: .env
    ports:
      - "4000:4000"
    environment:
      MONGO_URL: mongodb://nodejs:nodejspass@mongo/
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "4001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodejs
      MONGO_INITDB_ROOT_PASSWORD: nodejspass
